#!/bin/bash

echo "🔄 AWS Credentials Refresh Guide"
echo "================================"
echo ""
echo "The GitHub Actions workflow failed because AWS session tokens expire after a few hours."
echo "Here's how to refresh them:"
echo ""
echo "1. Get new AWS credentials using Ada:"
echo "   ada credentials update"
echo "   ada credentials print --account 257429339749 --role Admin"
echo ""
echo "2. Update GitHub Secrets with new credentials:"
echo "   - Go to: https://github.com/naveenraj44125-creator/github-actions-lightsail-demo/settings/secrets/actions"
echo "   - Update these secrets with new values:"
echo "     * AWS_ACCESS_KEY_ID"
echo "     * AWS_SECRET_ACCESS_KEY" 
echo "     * AWS_SESSION_TOKEN"
echo ""
echo "3. Trigger a new deployment:"
echo "   git commit --allow-empty -m 'Trigger deployment with refreshed credentials'"
echo "   git push origin main"
echo ""
echo "📊 Current Status:"
echo "✅ Lightsail Instance: Running (IP: 3.94.40.251)"
echo "✅ Application: Deployed and accessible"
echo "✅ Infrastructure: Fully operational"
echo "⚠️  GitHub Actions: Needs credential refresh"
echo ""
echo "🌐 Live Application: http://3.94.40.251:3000"
echo "🔍 Health Check: http://3.94.40.251:3000/health"
