#!/bin/bash

# GitHub Secrets Setup Script
# This script helps you set up the required secrets for GitHub Actions

set -e

echo "🔧 GitHub Actions Secrets Setup"
echo "================================"
echo ""

# Check if GitHub CLI is installed
if ! command -v gh &> /dev/null; then
    echo "❌ GitHub CLI (gh) is not installed."
    echo "Please install it from: https://cli.github.com/"
    exit 1
fi

# Check if user is authenticated
if ! gh auth status &> /dev/null; then
    echo "❌ You are not authenticated with GitHub CLI."
    echo "Please run: gh auth login"
    exit 1
fi

echo "✅ GitHub CLI is installed and authenticated"
echo ""

# Function to set a secret
set_secret() {
    local secret_name=$1
    local secret_description=$2
    local secret_value=""
    
    echo "Setting up: $secret_name"
    echo "Description: $secret_description"
    echo ""
    
    # Check if secret already exists
    if gh secret list | grep -q "$secret_name"; then
        echo "⚠️  Secret $secret_name already exists."
        read -p "Do you want to update it? (y/N): " update_secret
        if [[ ! $update_secret =~ ^[Yy]$ ]]; then
            echo "Skipping $secret_name"
            echo ""
            return
        fi
    fi
    
    # Get secret value from user
    if [[ $secret_name == *"KEY"* ]]; then
        echo "Please paste the private key content (press Ctrl+D when done):"
        secret_value=$(cat)
    else
        read -s -p "Enter value for $secret_name: " secret_value
        echo ""
    fi
    
    if [[ -z "$secret_value" ]]; then
        echo "❌ No value provided for $secret_name. Skipping."
        echo ""
        return
    fi
    
    # Set the secret
    echo "$secret_value" | gh secret set "$secret_name"
    echo "✅ Secret $secret_name has been set"
    echo ""
}

echo "📋 Required Secrets for GitHub Actions:"
echo ""
echo "1. AWS_ACCESS_KEY_ID - Your AWS Access Key ID"
echo "2. AWS_SECRET_ACCESS_KEY - Your AWS Secret Access Key"
echo "3. AWS_SESSION_TOKEN - Your AWS Session Token (if using temporary credentials)"
echo "4. LIGHTSAIL_SSH_KEY - Private SSH key for Lightsail instance access"
echo ""

read -p "Do you want to proceed with setting up these secrets? (y/N): " proceed
if [[ ! $proceed =~ ^[Yy]$ ]]; then
    echo "Setup cancelled."
    exit 0
fi

echo ""
echo "🔐 Setting up GitHub Secrets..."
echo ""

# Set up AWS credentials
set_secret "AWS_ACCESS_KEY_ID" "AWS Access Key ID for Lightsail access"
set_secret "AWS_SECRET_ACCESS_KEY" "AWS Secret Access Key for Lightsail access"

# Ask about session token
echo "AWS Session Token is only needed if you're using temporary credentials (like AWS SSO)."
read -p "Do you need to set AWS_SESSION_TOKEN? (y/N): " need_session_token
if [[ $need_session_token =~ ^[Yy]$ ]]; then
    set_secret "AWS_SESSION_TOKEN" "AWS Session Token for temporary credentials"
fi

echo ""
echo "🔑 SSH Key Setup"
echo "================"
echo ""
echo "The SSH key will be automatically generated by Terraform when the Lightsail instance is created."
echo "After the first deployment, you'll need to:"
echo "1. Download the private key from AWS Lightsail console"
echo "2. Set it as the LIGHTSAIL_SSH_KEY secret"
echo ""
echo "For now, we'll create a placeholder. You can update it later after the first deployment."

# Create a placeholder SSH key secret
placeholder_key="# Placeholder SSH key - Update this after first Terraform deployment
# 1. Go to AWS Lightsail console
# 2. Navigate to Account > SSH keys
# 3. Download the private key for 'my-app-instance-key'
# 4. Update this secret with the actual private key content"

echo "$placeholder_key" | gh secret set "LIGHTSAIL_SSH_KEY"
echo "✅ Placeholder SSH key secret created"

echo ""
echo "📋 Current GitHub Secrets:"
gh secret list

echo ""
echo "✅ GitHub Secrets setup completed!"
echo ""
echo "📝 Next Steps:"
echo "1. Commit and push your changes to trigger the GitHub Action"
echo "2. After the first deployment, update the LIGHTSAIL_SSH_KEY secret with the actual private key"
echo "3. The private key can be downloaded from: AWS Lightsail Console > Account > SSH keys"
echo ""
echo "🚀 Your GitHub Actions workflow is now ready to deploy to AWS Lightsail!"
